[build]
publish = ".hugo/public"
command = "git submodule update --init --recursive && cd .hugo && mv ../docs/zh content/zh/docs && mv ../docs/en content/en/docs && npm ci && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

