[build]
publish = "public"
command = "git submodule update --init --recursive && npm ci && npm run build && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

